#  CS446 Spring 2018

# Python Tutorial


Instructor: Dr. Jamal Abdul Nasir (IIU)

Problem 1) Data Types

Create two numerical variables x, y and assign integers to both.<br/>
Print x and y.<br/>
Perform 3 operations between x and y.<br/>
Print the results.

In [1]:
# Insert your code below.
x = 2
y = 3
print ("x=", x, "y=", y)
print (x ** y)
print (x ** 5 / y) 
print (x * (x - y))

x= 2 y= 3
8
10.666666666666666
-2


Problem 2) String  Functions

Assign the following content: "I really want to learn Data Science." to a string variable s.<br/>
Print the string s.<br/>
Replace "Data Science" in s with "Python" using the "replace" method of string and assign it to a new string t.<br/>
Print both strings s and t.

In [2]:
# Insert your code below.
s = "I really want to learn Data Science."
print (s)
t = s.replace("Data Science", "Python")
print (s,t,"Abc")
#print(t.indexOf('Python'))

I really want to learn Data Science.
I really want to learn Data Science. I really want to learn Python. Abc


Problem 3) Program Flow

Write a simple Python program to do the following.<br\>
From console ask user to input age as an integer.<br\>
If the age > 60, classify as senior;<br\>
else if 40 < age <= 60, classify as middle-age;<br\>
else if 20 < age <= 40, classify as youth;<br\>
else classify as junior.<br\>
The output may look like the following.

Input your age:<br/>
90<br/>
You are classified as Senior

In [ ]:
# Insert your code below.
age = int(input('Input your age:\n'))
if age > 60:
    level = 'Senior'
elif age > 40:
    level = 'Middle-aged'
elif age > 20:
    level = 'Youth'
else:
    level = 'Junior'

print ('You are classified as %s' % (level))

Problem 4) Arrays

Run the code below, you should get result character 'n'.  Now change the code to get result of characters 'b', 'l', 'm' and 'f', respectively.

In [4]:
companies = ['apple', 'google', 'facebook', 'amazon']
print (companies[-1])
print (companies[2])
#print (companies[3][2])

amazon
facebook


In [5]:
# Insert your code below.
companies = ['apple', 'google', 'facebook', 'amazon']
print (companies[2][4])
print (companies[1][-2]) # companies[0][-2]
print (companies[-1][1])
print (companies[-2][0])

b
l
m
f


# Loops

In [6]:
#While Loop
x= 1
while x <=10 :
    print (x) 
    x= x + 1

1
2
3
4
5
6
7
8
9
10


In [7]:
#For loop
for x in range(5):
    print (x)

0
1
2
3
4


In [ ]:
def max(x,y) : 
    if x < y :
        return y
    else :
        return x

In [ ]:
print(max('a','s'))

Problem 5) Numpy Operators

Create two Numpy arrays a, b and assign integers to them as follows:<br/>
a = [0, 1, 2, 3, 4], b = [5, 6, 7, 8, 9]<br/>
Print a and b.<br/>
Perform 4 Numpy array operations operations between a and b as follows.<br/>
a + b, 2\*a - b, a \* b, and a % b. <br/>
Print the results.<br/>

In [9]:
# Insert your code below.
import numpy as np
a = np.array([0, 1, 2, 3, 4])
b = np.array([5, 6, 7, 8, 9])
print (a, b)
print (a + b)
print (2*a - b)
print (a * b)
print (a % b)

print(a.shape)
print(a[0], a[1], a[2])
a[0] = 5
print(a)

[0 1 2 3 4] [5 6 7 8 9]
[ 5  7  9 11 13]
[-5 -4 -3 -2 -1]
[ 0  6 14 24 36]
[0 1 2 3 4]
(5,)
0 1 2
[5 1 2 3 4]


In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

In [ ]:
a = np.zeros((5, 3))
print(a)

In [10]:
b = np.ones((4, 5))
print(b)

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


In [ ]:
c = np.full((3, 6), 7)
print(c)

In [11]:
d = np.eye(5)
print(d)

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [ ]:
e = np.random.random((5, 5))
print(e)

## Array indexing

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print(a[0, 1])

In [ ]:
b = a[0:2, 1:3]
print(b)

In [ ]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)
print(x + y)
print(np.add(x, y))

In [ ]:
print(x - y)
print(np.subtract(x, y))

In [ ]:
print(x * y)
print(np.multiply(x, y))

In [ ]:
print(x / y)
print(np.divide(x, y))

In [ ]:
print(np.sqrt(x))

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

print(v.dot(w))
print(np.dot(v, w))

In [ ]:
print(x.dot(v))
print(np.dot(x, v))

In [ ]:
print(x.dot(y))
print(np.dot(x, y))

In [ ]:
x = np.array([[1, 2], [3, 4]])
print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

In [ ]:
x = np.array([[1, 2], [3, 4]])
print(x)
print(x.T)

In [ ]:
v = np.array([1, 2, 3])
print(v)
print(v.T)

## SciPy

### Distance between points

In [ ]:
from scipy.spatial.distance import pdist
from scipy.spatial.distance import squareform

x = np.array([[0, 1], [1, 0], [2, 0]])
print(x)

d = squareform(pdist(x, 'euclidean'))
print(d)

## Matplotlib

### Plotting

In [ ]:
import matplotlib.pyplot as plt

x = np.arange(0, 3 * np.pi, 0.1)
y = np.sin(x)

plt.plot(x, y)
plt.show()

In [ ]:
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

plt.plot(x, y_sin)
plt.plot(x, y_cos)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine'])
plt.show()

### Subplots

In [ ]:
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

plt.subplot(2, 1, 1)
plt.plot(x, y_sin)
plt.title('Sine')

plt.subplot(2, 1, 2)
plt.plot(x, y_cos)
plt.title('Cosine')
plt.show()

Problem 6) List Comprehension

The following code will create list1 of integers from 0 to 19, and convert it to list2 of the squares of the numbers in list1.  Change the code to produce list2 of squares only for odd numbers in list1.


In [ ]:
list1 = range(20)
#range(N) generates a list of numbers [0,1, ..., n-1]
print (list1)
list2 = [x**2 for x in list1]
print (list2)

In [ ]:
# Insert your code below.
list1 = range(20)
print list1
list2 = [x**2 for x in list1 if x % 2 == 1]
print list2

Problem 7) For loop and Dictionary (15pts)

Write Python code to solve the current problem. There are six kinds of fruits in the supermarket.  The prices per pound of the fruits and the amount in pounds we want to buy are defined as 2 dictionaries below.<br/>
prices = {"apple": 1.5, "banana": 1.6, "cherry": 3, "kiwi": 2.2, "orange": 1.2, "peach": 2}<br/>
amount = {"apple": 6, "cherry": 4, "orange": 5, "peach": 3}<br/>
How much money will we spend? Insert your code below.


In [ ]:
# Insert your code below.
prices = {"apple": 1.5, "banana": 1.6, "cherry": 3, "kiwi": 2.2, "orange": 1.2, "peach": 2}
amount = {"apple": 6, "cherry": 4, "orange": 5, "peach": 3}
total = 0
for key in prices:
    if key in amount:
        total = float(prices[key]) * float(amount[key]) + total    
total

In [2]:
import pandas as pd
import sys
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
from math import radians, cos, sin, asin, sqrt
import datetime
from sklearn.linear_model import LinearRegression
import seaborn as sns
sns.set(style="ticks")
%matplotlib inline

In [5]:
hubway_data = pd.read_csv('D:/Python Workspace/Code/mtcars.csv', low_memory=False)
hubway_data.head()

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

# A little data manipulation

In [ ]:
check_out_year = hubway_data['start_date'].apply(lambda s: int(s[-13:-9]))
age_col = (check_out_year - hubway_data['birth_date'])

In [ ]:
#And now for our first plot: a histogram of ages
plt.hist(age_col.dropna())
plt.title('Histogram of User Ages by Checkout')
plt.xlabel('Age in years')
plt.ylabel('Number of Checkouts')
plt.axvline(x=np.mean(age_col.dropna()), color='green', label='Average Age')
plt.legend()
plt.show()



In [ ]:
#And now for a second plot: scatter plot of age 
plt.scatter(age_col,hubway_data.duration)
plt.title('Scatter plot of Duration by User Ages')
plt.xlabel('Age in years')
plt.ylabel('Duration (in seconds)')
#plt.yscale('log')
plt.show()